runtime: php55
api_version: 1

handlers:
- url: /assets
  static_dir: assets
  
- url: /(.*\.(pdf|png|jpg))$
  static_files: \1
  upload: .+\.(pdf|png|jpg)$
  application_readable: true

- url: /.*
  script: index.php
  http_headers:
    Access-Control-Allow-Origin: *